### PR TITLE
Added the very basics of function score

### PR DESCRIPTION
**Pull request by Cronos87**
Can see the purpose of this function here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html.

### CODE REVIEW

**Review by isoos — APPROVED** [review]

**Comment by isoos** [comment]
Thanks! Do you need this to get published, or do you have something else in the works too?

**Comment by Cronos87** [comment]
I didn't plan to add something else at the moment. But I'm working on an application with Flutter and I add the missing feature while developing. I can't really tell when I will add something new 😅

Thank you for the fast merge as usual! You can publish it like this. I'm not sure I will work a lot on my project new few days, so I'm fine with this release.

**Comment by isoos** [comment]
Published, and thanks again! :)

**Comment by Cronos87** [comment]
Thank you for the fast publish!

**Pull request merged**
