### PR TITLE
Added docCount property on aggregations and size option to search

### PR DESCRIPTION
**Pull request by Cronos87**

### CODE REVIEW

**Comment by Cronos87** [comment]
I updated my fork using the Github interface fetchstream and looks like your master repository lost some commit from last week... I'm not sure to understand why. Maybe you know?

**Comment by isoos** [comment]
I'm not sure about why it become diverged from the main repo.
The change looks good, but could you also update the changelog and pubspec?

**Comment by Cronos87** [comment]
I just did it. Thank you for the review!

**Comment by isoos** [comment]
Great, thanks! I'll publish this shortly.

**Comment by Cronos87** [comment]
Thank you for the merge and for the fast publish every time!

**Pull request merged**
