### PR TITLE
Added ids query

### PR DESCRIPTION
**Pull request by Cronos87**
Added to Query the possibility to request ids.

See the Elasticsearch documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-ids-query.html.

Thank you!

### CODE REVIEW

**Comment by isoos** [comment]
Thanks! How urgent is it for you to get this published?

**Comment by Cronos87** [comment]
Awesome! Thank you for the merge.
No worry, I modified the package locally, like this I can play with it until a new version is released.

**Comment by isoos** [comment]
Released in 0.3.1

**Comment by Cronos87** [comment]
Thank you for the release!

**Pull request merged**
