### PR TITLE
adding basic auth paramater to client

### PR DESCRIPTION
**Pull request by apinprastya**
My Elastic search is behind the nginx with basic auth enabled. If you have better code, I am OK.

### CODE REVIEW

**Comment by isoos** [comment]
I think this would be much simpler if it would be only part of the `HttpTransport` class. Could you please move it to there, and then separate client method wouldn't need to have modifications wrt. headers.

**Comment by apinprastya** [comment]
hi @isoos, i have made the changes, please check

**Comment by isoos** [comment]
Looks good, thanks!

**Comment by isoos** [comment]
Published as `0.1.2`

**Pull request merged**
