### PR TITLE
Updated http_client dependency

### PR DESCRIPTION
**Pull request by uttufy**
This PR resolves this warning
```
../../.pub-cache/hosted/pub.dartlang.org/http_client-1.5.0/lib/pkg_http_adapter.dart:33:10: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
      rs.statusCode!,
         ^
```

### CODE REVIEW

**Comment by isoos** [comment]
I think if you hit `pub upgrade`, the version resolves to the latest anyway. Nevertheless, this one can be merged for now, and if there is no other pending change, I can release a new non-prerelease version with it.

**Comment by uttufy** [comment]
> I think if you hit `pub upgrade`, the version resolves to the latest anyway. Nevertheless, this one can be merged for now, and if there is no other pending change, I can release a new non-prerelease version with it.

There are no pending changes. Please proceed with pre-release
Thank you

**Comment by isoos** [comment]
Published 0.3.0.

**Comment by uttufy** [comment]
> Published 0.3.0.

Thank you :)

**Pull request merged**
