### PR TITLE
Added the method count to count the total of items for a given index

### PR DESCRIPTION
**Pull request by Cronos87**

### CODE REVIEW

**Comment by isoos** [comment]
I think this good, but I'd like to ask two more things:
- please add the same method to `Index`, similar to this: https://github.com/isoos/elastic_client/blob/master/lib/src/_index.dart#L12
- also update Changelog (and bump version) with a note.

Thanks!

**Comment by Cronos87** [comment]
Thank you for the feedback! I finish to work and I'll do it after that.

I can add it to the examples too if you want?

**Comment by isoos** [comment]
> I can add it to the examples too if you want?

Yeah, it would be great too!

**Comment by Cronos87** [comment]
OK! I'll do it 😉

**Comment by Cronos87** [comment]
I just pushed the modifications 😊

**Review by isoos — APPROVED** [review]
perfect! thank you, I'll publish shortly...

**Comment by Cronos87** [comment]
Awesome! Thank you to publish it soon! That's perfect!

**Pull request merged**
